sudo: required
services:
  - docker


before_install:
  - docker build -t vladadocker1981/docker-react -f Dockerfile.dev .

script:
  - docker run vladadocker1981/docker-react npm run test -- --coverage