sudo: required
services:
  - docker


before_install:
  - docker build -t vladadocker1981/docker-react -f Dockerfile.dev .

script:
  - docker run vladadocker1981/docker-react npm run test -- --coverage


deploy:
  provider: elasticbeanstalk
  region: "us-west-2-region-iz-linka-na-aws"
  app: "ime-na-aws"
  env: "ENV-iz-aws"
  bucket_name: "ime-iz-s3-aws"
  bucket_path: "ime-na-aws"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
